### ISSUE TITLE
Unable to Subscribe to Candle Channel

### ISSUE THREAD

**Issue by BitbeyHub** [nlsdfnbch/btfxwss#51]
```
test_is_connected_decorator_works_as_expected (__main__.BtfxWssTests) ... ok
test_subscribing_to_data_works (__main__.BtfxWssTests) ... ERROR

======================================================================
ERROR: test_subscribing_to_data_works (__main__.BtfxWssTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bxty9\Desktop\client_tests.py", line 27, in test_subscribing_to_data_works
    wss.tickers('BTCUSD').get(block=False)
  File "C:\ProgramData\Anaconda3\lib\site-packages\btfxwss\client.py", line 228, in tickers
    raise KeyError(pair)
KeyError: 'BTCUSD'

----------------------------------------------------------------------
Ran 2 tests in 13.095s

FAILED (errors=1)

```

**Comment by nlsdfnbch** [comment]
Hey @BitbeyHub !
Thanks for contributing! From looking at it,  this probably due to a pull request I merged earlier.  Good catch! 
Unfortunately I'm not near a computer till Sunday - until then a workaround may be to prepend a 't' to the symbol when calling the method.

**Comment by nlsdfnbch** [comment]
@BitbeyHub ,
if you have the time, could you confirm this issue is resolved now ? Also, please provide the code you use if the problem persists.

Thanks!

**Comment by nlsdfnbch** [comment]
I've checked the logs and found that Bitfinex doesn't like the way I send the subscription for candles:

```
DEBUG:btfxwss.client:_subscribe: {'key': 'trade:1m:tBTCUSD', 'event': 'subscribe', 'channel': 'candles'}
DEBUG:btfxwss.connection:_on_message(): Received new message {"channel":"candles","event":"error","msg":"key: invalid","code":10300} at 1506424899.4304948
```
Working on a solution atm

**Comment by BitbeyHub** [comment]
Sorry I am not very familiar with github and ... I found it might be my network reason after I made the script repeat the line of code again and again  only if it's in "KeyError" until it's connected successfully. Or so I fixed it ?

**Comment by nlsdfnbch** [comment]
@BitbeyHub, the release branch is the currently most up-to-date branch.

**Comment by nlsdfnbch** [comment]
I have opened a ticket with the `Bitfinex Support Team`, hopefully they'll find out what's going on here.
Although I'm quite positive it's something odd on my end, I just haven't been able to spot it.

**Comment by apotapov** [comment]
Fixed here: #64.

If you need a quick fix, you can modify your requirements.txt to replace:
`btfxwss==1.1.1`
with
`-e git://github.com/TapWealth/btfxwss.git#egg=btfxwss`

**Comment by apotapov** [comment]
Note, the fix above also makes the code Python2 compatible which was a requirement for my use case. If you want to make the fix yourself, here's the line that fixes it:

https://github.com/nlsdfnbch/btfxwss/pull/64/files#diff-fa3139a968f240692f4ad7f331d4ff7dR153

**Comment by kimms213** [comment]
Hello @nlsdfnbch,
Please check below!

In client._subscribe, the payload dictionary is passed to **conn.send** as separated parameters.
Unfortunately, candles channel has 'key' in parameter name.
This is overlapped with original parameter name 'key' in conn.send method, which is used for api key.

A quick fix for this problem is to change parameter name in conn.send, something like below.

def send(self, key=None, secret=None, list_data=None, auth=False, **kwargs):
->
def send(self, api_key=None, api_secret=None, list_data=None, auth=False, **kwargs):

Hope this helps!

**Comment by nlsdfnbch** [comment]
@kimms213 
You're right! Fixed it that way. Thanks for the help and pointers, people!

**Comment by Closius** [comment]
I still have this error. I created a python file for collecting data (candles) of one PAIR. Then I created a bash script for running (with nohup) my python file many times with different pairs.

When I run my bash script with lets say 4-5 pairs - its ok. But if I run it with 10 pairs first 4-5 pairs are running ok but next pairs raises an error like `[9]-  Exit 1                  nohup python3 $COLLECTOR $PAIR > $OUT_COLLECTOR`

I think it might be because I create many websocket connection for collecting one pair. Is it true or I should look another cause of this error?

**Comment by nlsdfnbch** [comment]
That is likely the case, yes - Bitfinex allows a maximum of 4-6 Requests per minute to the Websocket API, if I remember correctly. So You should connect once, and send a channel subscription for each pair on that one connection.

**Comment by Closius** [comment]
@nlsdfnbch Thank you Nils! 
I didn't find any limitation of requests for websocket on official website.
Do you know if there is some limit for channel subscription? I mean how many pairs I can subscribe per one ws connection.

**Comment by nlsdfnbch** [comment]
@Closius, I dug through my mails and found a ticket I had opened with them a few months ago, that's where I got the limit from:

> The limit is 15 connections per minute. You should hardly ever need to connect more that once or twice per minute. You should connect and keep the connection open for longer periods. You should only need to connect a few time per day, if at all. 
>
>Kind regards,
>
>Bjorn
>Bitfinex.com

So It's 15 per minute, but still, that might happen pretty quickly if the client is executed multiple times and tries to reconnect. 

You can subscribe to every single channel with all kinds of configurations - I haven't hit a limit for this on a single connection yet (and I run about 50 configurations)

**Comment by Closius** [comment]
@nlsdfnbch Thank you!
